CREATE GLOBAL TEMPORARY TABLE CARRITO_COMPRAS(
	USUARIO_CLIENTE VARCHAR(25),
	N_PELICULAS NUMBER(3,0),
	N_ALBUM NUMBER(3,0),
	N_VJUEGOS NUMBER(3,0),
	NT_PRODCUTOS NUMBER(3,0),
	LISTA_PRODUCTOS VARCHAR(300),
	MONTO_COMPRA NUMBER(7,2)
) ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE PRODUCTO_PRECIO(
	PRODUCTO VARCHAR(25),
	PRECIO NUMBER(7,2)
) ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE HISTORIAL_COMPRAS(
	LISTA_PRODUCTOS VARCHAR(300),
	MONTO_TOTAL NUMBER(7,2)
) ON COMMIT DELETE ROWS;

