CREATE SEQUENCE CLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 15
    CYCLE
  	NOCACHE ;
CREATE SEQUENCE DIRECCION_FAC_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 15
    CYCLE
    NOCACHE
    ;
CREATE SEQUENCE DIRECCION_ENT_SEQ
   START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 15
    CYCLE
    NOCACHE
    ;
CREATE SEQUENCE SEGUIMIENTO_SEQ
    START WITH 1001
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1015
    CYCLE
    NOCACHE
    ;
CREATE SEQUENCE LISTA_PRODUCTO_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 15
    CYCLE
    NOCACHE
;

CREATE SEQUENCE ORDEN_COMPRA_SEQ
   START WITH 100000001
    INCREMENT BY 1
    MINVALUE 100000001
    MAXVALUE 100000015
    CYCLE
    NOCACHE	
    ;
CREATE SEQUENCE TIPO_ENTREGA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 15
    NOORDER
;
CREATE SEQUENCE FACTURA_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 15
    CYCLE
    NOCACHE
;

CREATE SEQUENCE EMPRESA_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 15
    CYCLE
    NOCACHE
;
CREATE SEQUENCE PAQUETE_SEQ
  	START WITH 32041
    INCREMENT BY 1
    MINVALUE 32041
    MAXVALUE 32055
    CYCLE
    NOCACHE
;